site_name: Vector and Hybrid Search
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
plugins:
  - search
  - awesome-pages
  - roamlinks         # keep if you use [[Wiki Links]]; safe to leave on
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true   # LaTeX via MathJax/KaTeX wrappers
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
extra:
  arithmatex:
    inlineWrap: ["\\(", "\\)"]
    generic: true
docs_dir: docs
