site_name: Search with OpenSearch
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - content.code.copy
    - content.tabs.link
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: JetBrains Mono
plugins:
  - search
  - awesome-pages
  - roamlinks         # keep if you use [[Wiki Links]]; safe to leave on
markdown_extensions:
  # core niceties
  - admonition
  - attr_list
  - def_list
  - md_in_html

  # pymdownx goodies (lists, tabs, better emphasis)
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          separator: "-"
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  arithmatex:
    inlineWrap: ["\\(", "\\)"]
    generic: true
extra_css:
  - styles.css
docs_dir: docs
nav:
  - Home: README.md
  - Fundamentals:
      - Introduction to Search: intro_to_search.md
      - Vector Search Algorithms: index_deep_dive.md
      - Precision & Recall: precision_vs_recall.md
  - OpenSearch:
      - Introduction to OpenSearch: opensearch.md
      - RAG with OpenSearch: opensearch_rag.md
      - Production Deployment: opensearch_productionize.md
      - Code Examples: search_examples.md
  - Service Comparisons:
      - OpenSearch vs Kendra: opensearch_vs_kendra.md
      - OpenSearch vs Pinecone: opensearch_vs_pinecone.md
  - Reference:
      - Glossary: glossary.md
      - Further Reading: further_reads.md
  - Key Info:
      - License: LICENSE.md
      - README: README.md
      - Disclaimers: disclaimers.md
use_directory_urls: false
